export const TYPES = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  SET_LOADING: 'SET_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  LOADING: 'LOADING',

  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',

  SEARCH_HISTORY: 'SEARCH_HISTORY',
  REMOVE_HISTORY: 'REMOVE_HISTORY',

  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  INCREASE_ITEM_QUANTITY: 'INCREASE_ITEM_QUANTITY',
  DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
  REMOVE_ALL_CART_ITEMS: 'REMOVE_ALL_CART_ITEMS',
  CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',

  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',

  SET_SHIPPING_DETAILS: 'SET_SHIPPING_DETAILS',
  SET_PAYMENT_METHOD: 'SET_PAYMENT_METHOD',
  CLEAR_CHECK_OUT: 'CLEAR_CHECK_OUT',
};
